[package]
name = "fitsview-core"
version = "0.1.0"
edition = "2021"

[dependencies]
fitsrs = "0.4"
memmap2 = "0.9"
rayon = "1"
flate2 = "1"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "sync"] }
lru = "0.12"
anyhow = { workspace = true }
log = { workspace = true }

[dev-dependencies]
env_logger = { workspace = true }
