[package]
name = "fitsview-core"
version = "0.1.0"
edition = "2021"

[features]
default = []
network = ["dep:reqwest"]

[dependencies]
fitsrs = "0.4"
memmap2 = "0.9"
rayon = "1"
flate2 = "1"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "sync"] }
lru = "0.12"
anyhow = { workspace = true }
log = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
dirs = "5"
reqwest = { version = "0.12", default-features = false, features = ["json", "blocking", "rustls-tls"], optional = true }

[dev-dependencies]
env_logger = { workspace = true }


[[bench]]
name = "bench_core"
harness = false

[dev-dependencies.criterion]
version = "0.5"
features = ["html_reports"]
